name: CI/CD
on:
  push:
    branches:
      - main
      - deploy/github-ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Delete generated mock file if already exists
        run: find . -type f -name 'mock_*' -delete

      - name: Generate mock file
        run: |
          go install github.com/golang/mock
          go generate -v ./...

      - name: Run unit testing
        run: go test -v ./...

      - name: Delete generated mock file
        run: find . -type f -name 'mock_*' -delete

  Docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"